### ISSUE TITLE
Cannot read "cache" of undefined

### ISSUE THREAD

**Issue by DanLop618** [meister03/discord-hybrid-sharding#39]
After about an hour with the clister on, the process exits qith this error.

```bash
node:internal/event_target:646
2022-03-26T12:51:20.091867+00:00 app[worker.1]:   process.nextTick(() => { throw err; });
2022-03-26T12:51:20.091868+00:00 app[worker.1]:                            ^
2022-03-26T12:51:20.094581+00:00 app[worker.1]: TypeError [Error]: Cannot read property 'cache' of undefined
2022-03-26T12:51:20.094583+00:00 app[worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:13:41)
2022-03-26T12:51:20.094585+00:00 app[worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2022-03-26T12:51:20.094586+00:00 app[worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
2022-03-26T12:51:20.094587+00:00 app[worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
2022-03-26T12:51:20.094587+00:00 app[worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
2022-03-26T12:51:20.094588+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:199:18)
2022-03-26T12:51:20.094588+00:00 app[worker.1]:     at WebSocket.emit (node:events:394:28)
2022-03-26T12:51:20.094589+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1098:20)
2022-03-26T12:51:20.094589+00:00 app[worker.1]:     at Receiver.emit (node:events:394:28)
2022-03-26T12:51:20.094589+00:00 app[worker.1]:     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:528:14)
2022-03-26T12:51:20.094590+00:00 app[worker.1]: Emitted 'error' event on ClusterManager instance at:
2022-03-26T12:51:20.094590+00:00 app[worker.1]:     at Cluster._handleError (/app/node_modules/discord-hybrid-sharding/src/Core/Cluster.js:538:22)
2022-03-26T12:51:20.094590+00:00 app[worker.1]:     at Worker.emit (node:events:394:28)
2022-03-26T12:51:20.094591+00:00 app[worker.1]:     at Worker.[kOnErrorMessage] (node:internal/worker:298:10)
2022-03-26T12:51:20.094591+00:00 app[worker.1]:     at Worker.[kOnMessage] (node:internal/worker:309:37)
2022-03-26T12:51:20.094592+00:00 app[worker.1]:     at MessagePort.<anonymous> (node:internal/worker:210:57)
2022-03-26T12:51:20.094592+00:00 app[worker.1]:     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:460:20)
2022-03-26T12:51:20.094592+00:00 app[worker.1]:     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```
I followed the example as it is and tried everything to solve the problem but still no success on avoiding this behaviour.

**Discord.js Version**

-   Discord.js@13.3.0

**Additional context**
- Message Content Intents
- Verified Bot
- Hosting on Heroku
-  Node@16.0.0

**Comment by meister03** [comment]
This error has no relevance to the package.
The Cluster crashed because you di not handeld the error.

Probably a Djs bug, could you see if updating to a higher version fixes it?

**Comment by DanLop618** [comment]
It is weird because it started happening after creating the shard manager. I've updated a couple of things to see if the problem solves or at least i get a more detailed problem log.

**Comment by meister03** [comment]
Any update?
