### ISSUE TITLE
Broadcast eval not working when a cluster is offline

### ISSUE THREAD

**Issue by Mr-KayJayDee** [meister03/discord-hybrid-sharding#81]
Hello, i am trying to create an API that gets the status of my bot and it's clusters by a simple fetch request from the outside.

The issue here is that when i purposely kill/respawn a cluster like if it was restarting i cannot get the status of it because of the broadcast eval trying to eval on an offline cluster.

```
Error: CLUSTERING_NO_CHILD_EXISTS | ClusterId: 0
    at Cluster.eval (/home/bots/mrkayjaydee/xinko-ts/node_modules/discord-hybrid-sharding/dist/Core/Cluster.js:226:35)
    at ClusterManager._performOnClusters (/home/bots/mrkayjaydee/xinko-ts/node_modules/discord-hybrid-sharding/dist/Core/ClusterManager.js:366:37)
    at ClusterManager.broadcastEval (/home/bots/mrkayjaydee/xinko-ts/node_modules/discord-hybrid-sharding/dist/Core/ClusterManager.js:320:21)
    at ClusterHandler.handleMessage (/home/bots/mrkayjaydee/xinko-ts/node_modules/discord-hybrid-sharding/dist/Structures/IPCHandler.js:28:18)
    at Cluster._handleMessage (/home/bots/mrkayjaydee/xinko-ts/node_modules/discord-hybrid-sharding/dist/Core/Cluster.js:247:42)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Cluster file

```ts
import { ClusterManager } from "discord-hybrid-sharding";
import clientToken from "./config";
import log from "./utils/logger";

const manager = new ClusterManager(`${__dirname}/index.js`, {
	totalShards: 2,
	shardsPerClusters: 1,
	mode: "process",
	token: clientToken.token,
});

manager.on("clusterCreate", (cluster) =>
	log(
		`Launched Cluster ${cluster.id}\n-------------------------------------------------------------`,
		"cluster"
	)
);
manager.spawn({ timeout: -1 });
```

Here is my code that is working but not with an offline cluster, i wanna know if it's possible for each shards/cluster to get the status of it like: online, offline, reconnecting etc.

```ts
import Xinko from "./structures/Client";

const express = require("express");
const app = express();
const cors = require("cors");
const port = process.env.PORT || 8362;
import config from "./config";

let authToken = `Bot ${config.token}`;

let authTokenMiddleware = (req: any, res: any, next: any) => {
	if (req.headers.authorization === authToken) {
		next();
	} else {
		res.status(401).send("Unauthorized");
	}
};

(BigInt.prototype as any).toJSON = function () {
	return this.toString();
};

const startServer = async (client: Xinko) => {
	app.use(cors());
	app.get("/commands", authTokenMiddleware, (req: any, res: any) => {
		res.json(client.commands);
	});

	app.get("/stats", authTokenMiddleware, async (req: any, res: any) => {
		let guilds = await client.cluster.broadcastEval((c: any, context: any) => c.guilds.cache.size).then((guilds: any) => {
			return guilds.reduce((acc: any, guild: any) => acc + guild, 0);
		}).catch((err: any) => {
			console.log(err);
		});
		let users = await client.cluster.broadcastEval((c: any, context: any) => c.users.cache.size).then((users: any) => {
			return users.reduce((acc: any, user: any) => acc + user, 0);
		}).catch((err: any) => {
			console.log(err);
		});
		res.json({
			commands: client.commands.size,
			guilds: guilds,
			users: users,
			uptime: client.uptime,
			memory: process.memoryUsage().heapUsed,
			avatar_url: client.user.displayAvatarURL({ forceStatic: false }),
			latency: client.ws.ping,
			// for each cluster of shardList, get their infos
			shards: await client.cluster.broadcastEval((c: any, context: any) => {
				return {
					id: c.cluster.id,
					guilds: c.guilds.cache.size,
					uptime: c.uptime,
					latency: c.ws.ping,
					memory: process.memoryUsage().heapUsed,
				};
			}),
		});
	});

	app.listen(port, () => {
		console.log(`Xinko API listening at http://localhost:${port}`);
	});
};

export default startServer;
```

Here is the result when you GET to /stats

```json
{
    "commands": 68,
    "guilds": 9,
    "users": 112,
    "uptime": 28849,
    "memory": 31779648,
    "avatar_url": "https://cdn.discordapp.com/avatars/688495620989780002/17ae074b5fd4201dbcb94965a9b5cd9b.webp",
    "latency": 92,
    "shards": [
        {
            "id": 0,
            "guilds": 6,
            "uptime": 35720,
            "latency": 91,
            "memory": 32802176
        },
        {
            "id": 1,
            "guilds": 3,
            "uptime": 28850,
            "latency": 92,
            "memory": 31821240
        }
    ]
}
```

npm ls: 

```
xinko-ts@5.1.7 /home/bots/mrkayjaydee/xinko-ts
├── @napi-rs/canvas@0.1.41
├── @tsconfig/node16@1.0.4
├── @types/cron@2.0.1
├── @types/figlet@1.5.6
├── @types/i18next-fs-backend@1.1.2
├── @types/ms@0.7.31
├── @types/node@18.16.16
├── @types/superagent@4.1.18
├── @typescript-eslint/eslint-plugin@5.59.8
├── @typescript-eslint/parser@5.59.8
├── axios@1.4.0
├── chartjs-node-canvas@4.1.6
├── cors@2.8.5
├── cron@2.3.1
├── date-and-time@3.0.0
├── discord-hybrid-sharding@2.1.3
├── discord.js@14.11.0
├── dotenv@16.1.0
├── eslint@8.41.0
├── express@4.18.2
├── i18next-fs-backend@2.1.2
├── i18next@22.5.0
├── ioredis@5.3.2
├── ms@2.1.3
├── mysql2@3.3.3
├── stripe@11.18.0
├── superagent@8.0.9
└── typescript@5.0.4
```

Please tell me if you need more infos ^^

**Comment by meister03** [comment]
The new implementation, should work also when clusters are offline. I will need to test it, why it is not working 🤔

**Comment by Mr-KayJayDee** [comment]
Maybe my code is wrong somewhere 🤔

**Comment by Mr-KayJayDee** [comment]
What i did was spawning 3 clusters, kill a cluster after everything is spawned so i'm left with 2 alive and when the killed one is restarting i'm making my api request that will broadcast eval (and my error comes here)

```ts
import { ClusterManager } from "discord-hybrid-sharding";
import clientToken from "./config";
import log from "./utils/logger";

const manager = new ClusterManager(`${__dirname}/index.js`, {
	totalShards: 3,
	shardsPerClusters: 1,
	mode: "process",
	token: clientToken.token,
});

manager.on("clusterCreate", (cluster) =>
	log(
		`Launched Cluster ${cluster.id}\n-------------------------------------------------------------`,
		"cluster"
	)
);
manager.spawn({ timeout: -1 });

setTimeout(() => {
	const clusterToKill = manager.clusters.get(0);
	if (clusterToKill) {
		clusterToKill.kill({
			force: true,
		});
		log(`Killed Cluster ${clusterToKill.id}`, "cluster");
	}
}, 30000);
```
